--1
select EMPNO,LASTNAME, BIRTHDATE, SALARY from EMPLOYEE
where SALARY > 30000
order by SALARY desc ;

--2
select LASTNAME,FIRSTNME, WORKDEPT from EMPLOYEE
order  by WORKDEPT desc, LASTNAME desc;

--3
select distinct  EDLEVEL from EMPLOYEE
order by EDLEVEL desc ;

--4
select distinct EMPNO, PROJNO from EMPPROJACT
where EMPNO <= '000100'
order by EMPNO desc ;

--5
select LASTNAME,SALARY,BONUS from EMPLOYEE
where SEX = 'M';

--6
select LASTNAME,SALARY,COMM,HIREDATE from EMPLOYEE
where SALARY >= 20000 and HIREDATE >=  date('1979-01-01');

--7
select LASTNAME, SALARY, BONUS, COMM from EMPLOYEE
where SALARY >= 22000 and BONUS = 400 or BONUS = 500 and COMM <= 1900
order by LASTNAME;

--8
select LASTNAME, SALARY, BONUS, COMM from EMPLOYEE
where SALARY >= 22000 and BONUS = 400 or BONUS = 500 and COMM < 1900
order by LASTNAME;

--9
select PROJNO,ACTNO,EMSTDATE,EMENDATE
from EMPPROJACT
where ACTNO in (10,80,180)
order by ACTNO;

--10
select MGRNO, DEPTNO
from DEPARTMENT
where MGRNO is not null
order by MGRNO;

--11
select EMPNO,LASTNAME, SALARY, BONUS
from EMPLOYEE
where BONUS >= 800 and BONUS <= 1000
order by BONUS ;

--12
select EMPNO,LASTNAME,SALARY,WORKDEPT
from EMPLOYEE
where WORKDEPT >= 'A00' and WORKDEPT <= 'C01'
order by LASTNAME asc ;

--13
select PROJNO,PROJNAME
from PROJECT
where PROJNAME like '%SUPPORT%'
order by PROJNO asc;

--14
select *
from DEPARTMENT
where DEPTNO
order by DEPTNO asc;

--15
select LASTNAME, FIRSTNME,MIDINIT,SALARY,JOB from EMPLOYEE
where JOB not like '%MANAGER%' and JOB not like '%PRES%'
order by SALARY desc
limit 5;
--EX2 --1
select FIRSTNME,LASTNAME,DEPTNAME from EMPLOYEE EM,DEPARTMENT DE
order by EM.FIRSTNME asc ,EM.LASTNAME asc ,DE.DEPTNAME asc ;
--2
select FIRSTNME,LASTNAME,WORKDEPT,JOB,DEPTNAME
from EMPLOYEE,DEPARTMENT
where WORKDEPT between 'A02' and 'D22'
order by FIRSTNME asc ,JOB asc ,DEPTNAME asc ;
--3
select FIRSTNME,LASTNAME,MAJPROJ,DEPTNAME,EMPNO,MGRNO from EMPLOYEE,PROJECT,DEPARTMENT
where EMPNO = MGRNO order by DEPTNAME asc;
--10
select ACTNO,MGRNO,PROJNO,LASTNAME,EMSTDATE from EMPPROJACT,DEPARTMENT,EMPLOYEE
where EMSTDATE between '1982-10-15' and current_date
and DEPTNO = WORKDEPT and EMPLOYEE.EMPNO = MGRNO and EMPPROJACT.EMPNO = EMPLOYEE.EMPNO
order by ACTNO,EMSTDATE,MGRNO;
--11
select E1.WORKDEPT,E1.LASTNAME,E.LASTNAME,E1.HIREDATE,E.HIREDATE from EMPLOYEE as E join EMPLOYEE as E1 ON E1.WORKDEPT = E.WORKDEPT
where E.WORKDEPT = 'A00'
AND E.HIREDATE < (select EM.HIREDATE from EMPLOYEE as EM LEFT OUTER JOIN DEPARTMENT as DE on DE.MGRNO = EM.EMPNO
                 where DE.DEPTNO = 'A00')
AND E1.EMPNO = (SELECT EM.EMPNO from EMPLOYEE as EM LEFT OUTER JOIN DEPARTMENT as DE ON DE.MGRNO = EM.EMPNO
               where DE.DEPTNO = 'A00')
order by E.LASTNAME;